### ISSUE TITLE
test

### ISSUE THREAD

**Issue by TPGPL** [sr229/osu-wiki#2]
Add any details pertaining to wiki contributors above the break.

- [ ] Depends on #PR
- Closes #ISSUE

---

Add a sentence or two describing this change in plain english (or leave empty if the title is self-explanatory). This will be displayed on the [changelog](https://osu.ppy.sh/home/changelog). A single screenshot or short gif is also welcomed if appropriate.

**Comment by sr229** [comment]
This revision seems outdated. Thanks for testing.
